name: Publish NuGet - Release
on:
 release:
   types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish NuGet package
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npx grunt build
      - name: Publish NuGet package
        id: publish_nuget
        uses: laget-se/publish-nuget@v2
        with:
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          NUSPEC_FILE: nuget/bootstrap-select.nuspec
          PACKAGE_NAME: bootstrap-select
          VERSION_FILE_PATH: nuget/bootstrap-select.nuspec
          VERSION_REGEX: ^\s*<version>(.*)<\/version>\s*$
